"""
Signal detector module initialization.
"""
from .base import BaseSignalDetector
from .product_usage import (
    UsageSpikeDetector,
    UsageDropDetector,
    NearingPaywallDetector,
    DirectorSignupDetector,
    InvitesSentDetector,
    NewDepartmentUserDetector,
    HighNPSDetector,
    LowNPSDetector,
    InactivityDetector,
    UsageWoWDeclineDetector,
    TrialEndingDetector,
    UpcomingRenewalDetector,
    FreeDecisionMakerDetector,
    UpgradePageVisitDetector,
    ApproachingSeatLimitDetector,
    OverageDetector,
    HealthScoreDecreaseDetector,
    ARRDecreaseDetector,
    IncompleteOnboardingDetector,
    FutureCancellationDetector,
)

__all__ = [
    'BaseSignalDetector',
    'UsageSpikeDetector',
    'UsageDropDetector',
    'NearingPaywallDetector',
    'DirectorSignupDetector',
    'InvitesSentDetector',
    'NewDepartmentUserDetector',
    'HighNPSDetector',
    'LowNPSDetector',
    'InactivityDetector',
    'UsageWoWDeclineDetector',
    'TrialEndingDetector',
    'UpcomingRenewalDetector',
    'FreeDecisionMakerDetector',
    'UpgradePageVisitDetector',
    'ApproachingSeatLimitDetector',
    'OverageDetector',
    'HealthScoreDecreaseDetector',
    'ARRDecreaseDetector',
    'IncompleteOnboardingDetector',
    'FutureCancellationDetector',
]
